### ISSUE TITLE
Cursor moves to next line too early

### ISSUE THREAD

**Issue by AlexHartford** [zsoerenm/chips_input#10]
![image](https://user-images.githubusercontent.com/28658524/119034251-c73d6800-b973-11eb-9edd-2a1b1990f885.png)

Trying to figure out how to get this working where the cursor stays on the same line as the previous chip unless the user enters text that would cause the text to wrap to the next line. Any ideas would be awesome.

**Comment by zsoerenm** [comment]
I have not seen this behavior before. Could provide an example?

**Comment by AlexHartford** [comment]
I have isolated it to when you add your own InputDecoration to the ChipsInput

**Comment by AlexHartford** [comment]
I had attempted to add hintText to the decoration property in the textfield contained in chipsAndTextField. So it was my own code the entire time that broke it. My bad, would be nice to be able to have hint text though.
