### ISSUE TITLE
Async suggestions search

### ISSUE THREAD

**Issue by salihagic** [zsoerenm/chips_input#18]
Hi, very nice package.

But as it comes to fetching suggestions I think it would be very useful if the findSuggestions callback would have return type FutureOr<Iterable\<T\>> because now this package is not usable when it comes to fetching data asynchronousely which is the most usual case, let's say from an API.

Suggestion is to just change the return type of findSuggestions callback or allow custom builder for suggestions.

**Comment by zsoerenm** [comment]
This has been implemented just a week ago:
https://github.com/zsoerenm/chips_input/pull/17
