### ISSUE TITLE
maxChips ignored and documentation needs

### ISSUE THREAD

**Issue by Zelfapp** [zsoerenm/chips_input#3]
Awesome package. Thank you. Trying to understand how to use. Some documentation on the following issues I've run into would be helpful.

As you can see here the suggestion builder is not constrained to the padding on the right side, which exists. **How do I style the suggestion builder?**

![image](https://user-images.githubusercontent.com/11559805/113139501-71a2d580-91e4-11eb-930b-5ecf7f6dfe25.png)

Regarding focusNode handling, how do you init the suggestionBuilder from an onTap event on an icon, for example, like you see below?

I've added a focusNode and listener to it, however, tapping out of ChipsInput area or in does nothing. The listener is not registering whether there is focus or not.

```
ChipsInput(
  maxChips: 3,
  readOnly: true,
  showCursor: false,
  focusNode: _sendToFieldFocusNode,
```

![image](https://user-images.githubusercontent.com/11559805/113139828-d8c08a00-91e4-11eb-9ba2-8b155087ca58.png)

**How do you close the suggestionBuilder?** I'm tapping around screen, but once it is open it just stays open.

**I have maxChips set to 3, but I'm able to add 4+**

**chips_input.dart**: code below seems to contain the logic error for controlling number of chips that can be selected if that is the intent of maxChips.
```
maxLength: (widget.maxChips != null &&
                      widget.maxChips! <= _chips.length &&
                      _chips.length > 0)
                  ? _chips.length
                  : widget.maxLength,
```

![image](https://user-images.githubusercontent.com/11559805/113143334-3fe03d80-91e9-11eb-98cf-cdc68427039f.png)

**Comment by zsoerenm** [comment]
Alright I was able to reproduce the bug with `maxChips`. This should be fixed in v0.0.5.
I also added an option for the `optionsViewBuilder`. You can use that instead of the `suggestionBuilder` for more customization (see Readme).
