### ISSUE TITLE
Suggestions are incorrectly offset from the start of the textfield

### ISSUE THREAD

**Issue by AlexHartford** [zsoerenm/chips_input#9]
![image](https://user-images.githubusercontent.com/28658524/118145446-3d215c80-b3d3-11eb-9608-4794debedd01.png)

To replicate, add horizontal padding around the ChipsInput.

e.g.
```dart
Padding(
  padding: const EdgeInsets.symmetric(horizontal: 16.0),
  child: ChipsInput(
```

**Comment by AlexHartford** [comment]
This might just be an autocomplete issue? Can't find anywhere in the package that could cause this.

**Comment by zsoerenm** [comment]
Yes, this might be part of autocomplete. You could use `optionsViewBuilder` instead of `suggestionBuilder` to fix the padding on the right, I guess (see Readme.md).

**Comment by AlexHartford** [comment]
I have done that and face the same situation. If you have 0 horizontal padding, the autocomplete centers, it doesn't go edge to edge. If you add padding, you get the result in the screenshot above.

**Comment by AlexHartford** [comment]
Confirmed this is an autocomplete issue, the overlay doesn't get the padding from the parent autocomplete.

**Comment by zsoerenm** [comment]
Thank you for digging into this. Is there an existing issue at github that tracks the autocomplete issue?

**Comment by AlexHartford** [comment]
https://github.com/flutter/flutter/issues/78746
https://github.com/flutter/flutter/issues/79227

Both of these go into it
